### ISSUE TITLE
Pourquoi l'option "Aucun" n'est pas dans le modèle directement ?

### ISSUE THREAD

**Issue by florianpanchout** [incubateur-ademe/nosgestesclimat#2054]
Pourquoi le bouton "Aucun" (qui s'affiche par exemple pour la question vacances) n'est pas une suggestion dans le modèle ?

Ça ne semble pas poser de problème conceptuel vu que c'est déjà le cas pour la mosaïque boissons chaudes.

**Comment by JuliePouliquen** [comment]
Tu veux dire que ce serait un des choix de la mosaïque ?

**Comment by florianpanchout** [comment]
Non, une des suggestions. Comme ici par exemple 

<img width="866" alt="Screenshot 2023-09-04 at 13 04 23" src="https://github.com/incubateur-ademe/nosgestesclimat/assets/8115933/bd8fcc8a-8621-4854-b9a6-d2cbbb84e7b6">

**Comment by JuliePouliquen** [comment]
Bonne question. Que j'ajoute au moulin des réflexions sur la charte de comportement côté modèle (et questions poke @jeremiecook).

**Comment by Clemog** [comment]
> Que j'ajoute au moulin des réflexions sur la charte de comportement côté modèle (et questions poke jeremiecook).

Pour le coup c'est un côté plus technique que design, on est en plein dans la dualité modèle / site. 

Pour répondre à la question initiale, ce 'Aucun' est une "sécurité" dans le cas ou la suggestion qui correspond à aucun n'est pas définie dans le modèle: en effet s'il n'y a pas cette option, le bouton "je ne sais pas" de la mosaïque ne 

La question design est bien dans le côté : est ce que ce bouton "Aucun" ne devrait pas être une carte de la mosaïque ?

Exemple pour la caravane / camping car (pas de suggestion définie):

```yaml
transport . vacances:
  mosaique:
    type: selection
    clé: propriétaire
  question: Que possédez-vous pour vos week-ends, vos vacances ?
  icônes: 🏖
  description: |
    On vous propose ici de sélectionner ce que vous possédez pour vos vacances. Pour le moment, le choix est restreint à la caravane et au camping car.

    > À noter que leur empreinte est séparée en deux : la partie usage est ajoutée au transport tandis que la partie construction est intégrée au logement.

    💡 Si vous ne possédez ni camping car, ni caravane, ou bien si vous les louez, vous pouvez cliquer sur "aucun" juste en dessous de cette question, puis "Suivant". La location n'est pas encore disponible dans notre modèle**.

  formule:
    somme:
      - caravane . empreinte . usage réel
      - camping car . empreinte . usage réel
      - van
 ```
 
 Exemple pour les animaux domestiques (suggestion "aucun" définie):

```yaml
divers . animaux domestiques . empreinte:
  titre: Empreinte annuelle des animaux du foyer
  icônes: 😺🐶
  question: Combien d'animaux vivent avec vous, au sein de votre foyer ?
  description: |
    Chien ou chat, c'est le moment de prendre en compte nos fidèles compagnons.

    > 🦴 L'impact votre animal est en grande partie lié à sa gamelle !
  mosaique:
    type: nombre
    clé: nombre
    suggestions:
      pas d'animaux:
        petit chien . nombre: 0
        chien moyen . nombre: 0
        gros chien . nombre: 0
        chats . nombre: 0
  formule:
    somme:
      - chats
      - chiens
```
