### ISSUE TITLE
Refonte / Bug sur suggestion

### ISSUE THREAD

**Issue by jeannelf** [incubateur-ademe/nosgestesclimat#2083]
Par exemple sur la page Boissons chaudes
Je choisis la sugg "Beaucoup de café"

En v1 (comportement souhaité) 
Les trucs pré remplis changent pour : 28 cafés (4 par jour), et 0 thé

![Image](https://github.com/incubateur-ademe/nosgestesclimat-site/assets/144152881/17ee5746-f9fc-406b-9efd-8cc6e79720e2)

En v2 : on change cafés à 28, et thé on laisse au truc par défaut à 7
    
=>  quel que soit le travial en cours sur le svaleurs par défaut, les suggestions doivent se comporter en remplacant toutes les valeurs correctement (positivement et à 0 sinon)

![Image](https://github.com/incubateur-ademe/nosgestesclimat-site/assets/144152881/b2349d77-4121-434c-8523-7d418d4fcb1b)

**Comment by jeannelf** [comment]
possible de bosser sur ce ticket dans la semaine @JuliePouliquen ou @Clemog ? vu que le lancement de la refonte en est dépendant ?

**Comment by Clemog** [comment]
Oui je regarde ça demain

**Comment by jeannelf** [comment]
on est d'accord que cest pas mergé ? car je le vois pas sur preprod

**Comment by Clemog** [comment]
cf https://github.com/incubateur-ademe/nosgestesclimat/pull/2088 :)

**Comment by jeannelf** [comment]
A partir de 12 secondes sur la vidéo : 
Ca marche au premeir usage
Mais si je change d'avis et utilise une autre suggestion, ca n'écrase pas les autres propositions et je lme retrouve au dessus de la limite

https://www.loom.com/share/037f66f4c65d4f2ba70169bd972e6663?sid=4dddbcba-b020-44db-a9f8-f59af2193b02

**Comment by Clemog** [comment]
Hum yes, je vois bien le souci

Actuellement, au clic sur une suggestion, on commence par tout remettra à 0, puis on ajoute ce qui est défini en suggestions à chaque carte de la mosaïque ..

2 solutions:

- Réimplémenter ce fonctionnement côté site (je te vois venir @florianpanchout donc cf 2eme point 😆)
- Ajouter pour chque suggestions toutes les règles qui doivent être remises à 0 (un peu lourd..)

Actuellement :

```yaml
    suggestions:
      je suis végétalien:
        végétalien . nombre: 14
      je suis végétarien:
        végétalien . nombre: 3
        végétarien . nombre: 11
      je mange peu de viande:
        végétalien . nombre: 1
        végétarien . nombre: 7
        viande 1 . nombre: 4
        poisson 1 . nombre: 1
        poisson 2 . nombre: 1
      je mange de la viande régulièrement:
        végétarien . nombre: 4
        viande 1 . nombre: 6
        viande 2 . nombre: 2
        poisson 1 . nombre: 1
        poisson 2 . nombre: 1
      je mange beaucoup de viande:
        viande 1 . nombre: 6
        viande 2 . nombre: 6
        poisson 1 . nombre: 1
        poisson 2 . nombre: 1
   ```
   
   
   Solution de la deuxième proposition :
   
   ```yaml
       suggestions:
      je suis végétalien:
        végétalien . nombre: 14
        végétarien . nombre: 0
        viande 1 . nombre: 0
        viande 2 . nombre: 0
        poisson 1 . nombre: 0
        poisson 2 . nombre: 0
      je suis végétarien:
        végétalien . nombre: 3
        végétarien . nombre: 11
        viande 1 . nombre: 0
        viande 2 . nombre: 0
        poisson 1 . nombre: 0
        poisson 2 . nombre: 0
      je mange peu de viande:
        végétalien . nombre: 1
        végétarien . nombre: 7
        viande 1 . nombre: 4
        viande 2 . nombre: 0
        poisson 1 . nombre: 1
        poisson 2 . nombre: 1
      je mange de la viande régulièrement:
        végétalien . nombre: 0
        végétarien . nombre: 4
        viande 1 . nombre: 6
        viande 2 . nombre: 2
        poisson 1 . nombre: 1
        poisson 2 . nombre: 1
      je mange beaucoup de viande:
        végétalien . nombre: 0
        végétarien . nombre: 0
        viande 1 . nombre: 6
        viande 2 . nombre: 6
        poisson 1 . nombre: 1
        poisson 2 . nombre: 1
     ```
